import { Router } from "express";
const router = Router();
import languageRouter from "./language/router";
import dataRouter from "./data/router";
import rsvpRouter from "./rsvp/router";
import giftRouter from "./gift/router";
router.use("/language", languageRouter);
router.use("/data", dataRouter);
router.use("/rsvp", rsvpRouter);
router.use("/gift", giftRouter);
export default router;
